// <auto-generated />
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Nodes;

// ReSharper disable InvalidXmlDocComment

namespace PipeLoom.JsonQuery.Parsing;

// AI generated

/// <summary>
/// Parses JsonQuery Text Format into the JSON Format AST (System.Text.Json.Nodes),
/// per https://jsonquerylang.org/docs/#json-format.
///
/// Fully standalone: depends only on JsonQueryLexer (this project) and
/// System.Text.Json.Nodes (BCL). Zero dependency on JsonQuery.Net.
///
/// Why standalone, not built on JsonQuery.Net's JsonQueryReader/JsonQueryParser:
///   - JsonQueryParser (their parser) constructs IJsonQueryable instances via
///     Activator.CreateInstance on runtime-closed generic types — confirmed to
///     break under Native AOT, and structural to their extensibility design
///     (not a narrow bug that's realistically fixable upstream).
///   - JsonQueryReader (their tokenizer) was tried directly and found to have a
///     real correctness bug independent of AOT: it tracks an internal
///     "MeetOperator" marker on a stack to validate operator sequencing, but
///     that marker is only popped in SOME of Read()'s branches (comma, '}',
///     ')', ']', '|', finding a new operator) — NOT in the property-path branch
///     or the generic value-scan branch. A query like `.age + .nage * pick(.a,
///     .b)` (operator, then a property-path operand, then another operator)
///     leaves a stale marker on the stack that corrupts the next operator
///     lookup, throwing a confusing "Unexpected ''" deep inside the reader.
///     This is not something callers can work around by sequencing Read() calls
///     differently — it's a bug in the reader's own state machine.
///   Given both halves of JsonQuery.Net were found to be unreliable (one for
///   AOT, one for plain correctness), this parser has zero dependency on that
///   library at all — it owns tokenization (via JsonQueryLexer) and parsing
///   end to end, with a fully stateless token LIST (not a stateful cursor with
///   hidden internal tracking) as its only input.
///
/// AOT safety: every literal added to a JsonArray/JsonObject goes through an
/// explicit, non-generic JsonValue.Create(string|decimal|bool) overload via the
/// Str()/Call() helpers below — never through JsonArray's collection-initializer
/// implicit conversions, which route through JsonValue.Create&lt;T&gt;'s
/// generic/reflection-touching fallback path and are NOT safe under
/// PublishAot=true.
///
/// Grammar (highest to lowest precedence), cross-checked against the
/// reference implementation's operators.ts and against parser.test.json's
/// `operator` test group:
///   8  ^                         (non-chaining — parses at most one RHS)
///   7  * / %                     (left-to-right, pairwise-folded)
///   6  + -                       (left-to-right, pairwise-folded)
///   5  > >= < <= in "not in"     (non-chaining)
///   4  == !=                     (non-chaining)
///   3  and                       (left-to-right, vararg)
///   2  or                        (left-to-right, vararg)
///   1  |  (pipe)                 (left-to-right, vararg)
/// Only and/or/pipe are vararg (operators.ts: varargOperators = ['|', 'and',
/// 'or']) — every other operator, including same-operator chains like
/// `1 + 2 + 3`, folds pairwise/left-associatively instead:
/// `1 + 2 + 3` -> ["add", ["add", 1, 2], 3], NOT ["add", 1, 2, 3].
///
/// Level 1 also does double duty as the ONLY place that resolves an
/// implicitly-piped trailing property access, e.g. `groupBy(.city).myCity`
/// (no explicit '|' between the function call and the property). See
/// ParsePipe for why this belongs at the pipe level specifically and nowhere
/// else in the precedence chain — ported from the reference implementation's
/// parseOperator(), which gates the same check on `'pipe' in currentOperators`.
///
/// STILL UNVERIFIED — worth checking against the official test suite
/// (https://github.com/jsonquerylang/jsonquery/tree/develop/test-suite) before
/// relying on this in production:
///   - Exact AST shape for unary minus on a non-literal operand (e.g. -(.age));
///     JsonQuery's docs don't show a dedicated unary-minus node, so this
///     currently emits ["subtract", 0, x] as a reasonable guess.
/// </summary>
internal sealed class JsonQueryParser
{
    private readonly List<Token> _tokens;
    private int _pos;

    private JsonQueryParser(List<Token> tokens)
    {
        _tokens = tokens;
        _pos = 0;
    }

    /// <summary>Entry point: parse a full query string into its JSON Format AST.</summary>
    public static JsonNode? Parse(string source)
    {
        var tokens = new JsonQueryLexer(source).Tokenize();
        var parser = new JsonQueryParser(tokens);
        JsonNode? result = parser.ParsePipe();
        parser.Expect(TokType.Eof, "end of input");
        return result;
    }

    // ---- AOT-safe node construction --------------------------------------
    // JsonArray's collection initializer and JsonNode's implicit conversions
    // from primitive types (string/bool/decimal/etc.) route through
    // JsonValue.Create<T>, whose generic/implicit path can hit reflection-based
    // fallbacks disabled under Native AOT. The explicit, non-generic overloads
    // (JsonValue.Create(string?), JsonValue.Create(decimal), JsonValue.Create(bool))
    // have dedicated non-reflective fast paths — Str()/Call() below route
    // through those exclusively so no call site can accidentally regress to an
    // implicit conversion.

    private static JsonValue Str(string value) => JsonValue.Create(value)!;

    // JsonArray.Add<T>(T) is the generic overload, annotated
    // [RequiresUnreferencedCode]/[RequiresDynamicCode] regardless of what T
    // actually is — the analyzer can't see through to know T is always a safe
    // JsonValue here, so calling Add(Str(keyword)) infers Add<JsonValue> and
    // trips the warning even though nothing unsafe is actually happening.
    // JsonArray also exposes a non-generic Add(JsonNode?) (via its underlying
    // IList<JsonNode?> surface), which has no such annotation. Explicitly
    // typing the local as JsonNode? forces overload resolution to pick that
    // non-generic path instead of inferring the generic one.
    private static void AddNode(JsonArray arr, JsonNode? node) => arr.Add(node);

    private static JsonArray Call(string keyword, params JsonNode?[] args)
    {
        var arr = new JsonArray();
        JsonNode? keywordNode = Str(keyword);
        AddNode(arr, keywordNode);
        foreach (var a in args) AddNode(arr, a);
        return arr;
    }

    // ---- token stream helpers ---------------------------------------------

    private Token Current => _tokens[_pos];

    private Token Advance()
    {
        var t = _tokens[_pos];
        if (_pos < _tokens.Count - 1) _pos++;
        return t;
    }

    private bool Check(TokType type) => this.Current.Type == type;

    private bool CheckIdent(string keyword) =>
        this.Current.Type == TokType.Ident && string.Equals(this.Current.Text, keyword, StringComparison.Ordinal);

    private bool CheckOp(string symbol) =>
        this.Current.Type == TokType.Op && string.Equals(this.Current.Text, symbol, StringComparison.Ordinal);

    private Token Expect(TokType type, string what)
    {
        if (this.Current.Type != type)
            throw new JsonQueryParseException($"Expected {what} but got {this.Current}", this.Current.Position);
        return this.Advance();
    }

    // ---- precedence levels -------------------------------------------------
    // Each level is a thin wrapper; only 'and'/'or'/'|'/'+'/'-' loop (vararg,
    // left-associative). '^' and the non-chaining comparison groups parse a
    // single optional right-hand side and then stop, per the docs' precedence
    // table ("do not support more than two values").

    private JsonNode? ParsePipe()
    {
        var parts = new List<JsonNode?> { this.ParseOr() };

        while (true)
        {
            if (this.Check(TokType.Dot))
            {
                // A '.' surfacing back up here (rather than having already
                // been consumed by ParsePrimary's own property-chain branch)
                // means the previous part was something that doesn't look
                // ahead for a trailing property access — a function call, a
                // parenthesized expression, an object/array literal, etc.
                // e.g. `groupBy(.city).myCity`: ParseFunctionCall returns
                // right after the closing ')', with ".myCity" untouched.
                // JsonQuery treats that as an implicit pipe step: run the
                // property access against the previous step's result, same
                // as if you'd written `groupBy(.city) | .myCity`. This is
                // deliberately only checked here at the pipe precedence
                // level (not in ParseOr/ParseAnd/etc.) — matches the
                // reference implementation, whose parseOperator() only does
                // this check at the level where 'pipe' is a registered
                // operator, i.e. the lowest/outermost one.
                parts.Add(this.ParsePropertyChain());
                continue;
            }

            if (this.Check(TokType.Pipe))
            {
                this.Advance();
                parts.Add(this.ParseOr());
                continue;
            }

            break;
        }

        if (parts.Count == 1) return parts[0];

        return Call("pipe", parts.ToArray());
    }

    private JsonNode? ParseOr()
    {
        var parts = new List<JsonNode?> { this.ParseAnd() };
        while (this.CheckIdent("or"))
        {
            this.Advance();
            parts.Add(this.ParseAnd());
        }

        if (parts.Count == 1) return parts[0];

        return Call("or", parts.ToArray());
    }

    private JsonNode? ParseAnd()
    {
        var parts = new List<JsonNode?> { this.ParseEquality() };
        while (this.CheckIdent("and"))
        {
            this.Advance();
            parts.Add(this.ParseEquality());
        }

        if (parts.Count == 1) return parts[0];

        return Call("and", parts.ToArray());
    }

    // ==, != : non-chaining (parse at most one)
    private JsonNode? ParseEquality()
    {
        JsonNode? left = this.ParseRelational();

        string? opName = null;
        if (this.CheckOp("==")) opName = "eq";
        else if (this.CheckOp("!=")) opName = "ne";

        if (opName is null) return left;

        this.Advance();
        JsonNode? right = this.ParseRelational();
        return Call(opName, left, right);
    }

    // >, >=, <, <=, in, not in : non-chaining (parse at most one)
    private JsonNode? ParseRelational()
    {
        JsonNode? left = this.ParseAdditive();

        string? opName = this.TryReadRelationalOperator();
        if (opName is null) return left;

        JsonNode? right = this.ParseAdditive();
        return Call(opName, left, right);
    }

    private string? TryReadRelationalOperator()
    {
        if (this.CheckOp(">=")) { this.Advance(); return "gte"; }
        if (this.CheckOp("<=")) { this.Advance(); return "lte"; }
        if (this.CheckOp(">")) { this.Advance(); return "gt"; }
        if (this.CheckOp("<")) { this.Advance(); return "lt"; }

        if (this.CheckIdent("in"))
        {
            this.Advance();
            return "in";
        }

        if (this.CheckIdent("not"))
        {
            // Lookahead for "not in" without permanently consuming "not" if
            // it's not followed by "in". Our token list makes this trivial —
            // just peek one slot further, no destructive read/backtrack needed
            // (unlike JsonQuery.Net's reader, which required a Next()-based
            // non-destructive lookahead copy for the equivalent case).
            if (_pos + 1 < _tokens.Count &&
                _tokens[_pos + 1].Type == TokType.Ident &&
                string.Equals(_tokens[_pos + 1].Text, "in", StringComparison.Ordinal))
            {
                this.Advance(); // consume "not"
                this.Advance(); // consume "in"
                return "not in";
            }
            // Bare "not" without a following "in" — not a valid operator on
            // its own in this grammar; leave it unconsumed and let the caller
            // report it as an unexpected token wherever parsing next expects
            // something else.
        }

        return null;
    }

    // +, - : left-to-right, vararg-folded when the whole chain uses one operator
    private JsonNode? ParseAdditive()
    {
        JsonNode? left = this.ParseMultiplicative();

        while (this.CheckOp("+") || this.CheckOp("-"))
        {
            string op = this.CheckOp("+") ? "add" : "subtract";
            this.Advance();
            JsonNode? right = this.ParseMultiplicative();
            left = Call(op, left, right);
        }

        return left;
    }

    // *, /, % : left-to-right, folded pairwise, same shape as ParseAdditive.
    private JsonNode? ParseMultiplicative()
    {
        JsonNode? left = this.ParsePower();

        while (this.CheckOp("*") || this.CheckOp("/") || this.CheckOp("%"))
        {
            string op = this.CheckOp("*") ? "multiply" : this.CheckOp("/") ? "divide" : "mod";
            this.Advance();
            JsonNode? right = this.ParsePower();
            left = Call(op, left, right);
        }

        return left;
    }

    // ^ : non-chaining per docs ("do not support more than two values"); use
    // parentheses to nest, e.g. (2 ^ 3) ^ 4
    private JsonNode? ParsePower()
    {
        JsonNode? left = this.ParseUnary();

        if (this.CheckOp("^"))
        {
            this.Advance();
            JsonNode? right = this.ParseUnary();
            return Call("pow", left, right);
        }

        return left;
    }

    // unary minus: '-' followed immediately by a primary
    private JsonNode? ParseUnary()
    {
        if (this.CheckOp("-"))
        {
            this.Advance();
            JsonNode? operand = this.ParseUnary();

            if (operand is JsonValue v && v.TryGetValue<decimal>(out decimal d))
                return JsonValue.Create(-d);

            // Non-literal negation, e.g. -(.age) — JsonQuery's docs don't show
            // a dedicated unary-minus AST node, so this falls back to
            // ["subtract", 0, x]. Verify against the test suite's
            // parse.test.json if this matters for your queries.
            return Call("subtract", JsonValue.Create(0m), operand);
        }

        return this.ParsePrimary();
    }

    // ---- primary: functions, properties, objects, arrays, literals, parens ----

    private JsonNode? ParsePrimary()
    {
        switch (this.Current.Type)
        {
            case TokType.LParen:
                this.Advance();
                JsonNode? inner = this.ParsePipe();
                this.Expect(TokType.RParen, "')'");
                return inner;

            case TokType.Dot:
                return this.ParsePropertyChain();

            case TokType.LBrace:
                return this.ParseObject();

            case TokType.LBracket:
                return this.ParseArray();

            case TokType.QuotedString:
                return Str(this.Advance().StringValue!);

            case TokType.Number:
                return JsonValue.Create(this.Advance().NumberValue);

            case TokType.True:
                this.Advance();
                return JsonValue.Create(true);

            case TokType.False:
                this.Advance();
                return JsonValue.Create(false);

            case TokType.Null:
                this.Advance();
                return null; // JSON null literal — a genuinely null JsonNode

            case TokType.Ident:
                return this.ParseFunctionCall();

            default:
                throw new JsonQueryParseException($"Unexpected token {this.Current}", this.Current.Position);
        }
    }

    // .prop1.prop2 / ."quoted prop" / .2 (array index)
    //   ->  ["get", "prop1", "prop2"] / ["get", 2]
    // Identifier and quoted-string segments become JSON strings; a purely
    // numeric segment (array index, e.g. `.array.2`) becomes a JSON NUMBER,
    // not a stringified digit — per parser.test.json's `property` group:
    //   .9        -> ["get", 9]
    //   .array.2  -> ["get", "array", 2]
    private JsonNode ParsePropertyChain()
    {
        var segArgs = new List<JsonNode?>();

        while (this.Check(TokType.Dot))
        {
            Token dot = this.Advance();
            this.RequireNoGapAfterDot(dot);
            segArgs.Add(this.ReadPropertySegment());
        }

        return Call("get", segArgs.ToArray());
    }

    // The reference implementation parses a property segment as a single
    // character scan starting IMMEDIATELY after consuming '.' — it never
    // skips whitespace there (skipWhitespace() only runs AFTER a segment,
    // before checking for a next '.'). So `. "name"` (space right after the
    // dot) is invalid, while `.address .city` (space before the NEXT dot) is
    // fine — the two positions have different rules. Our lexer pre-tokenizes
    // and always skips whitespace between tokens, which erases that
    // distinction by the time the parser sees the token stream. Recovered
    // here: a Dot token is always exactly one character wide, so if the
    // following token doesn't start at dot.Position + 1, something (only
    // ever whitespace, given what the lexer accepts) separated them.
    private void RequireNoGapAfterDot(Token dot)
    {
        if (this.Current.Position != dot.Position + 1)
            throw new JsonQueryParseException("Expected property name after '.'", dot.Position + 1);
    }

    // Returns the segment as the JsonNode that belongs directly in the "get"
    // argument list — a JSON string for identifier/quoted-string segments, a
    // JSON number for a Number-token segment. (Previously this returned a
    // plain string and the caller always wrapped it via Str(...), which lost
    // the string-vs-number distinction for numeric segments.)
    private JsonNode ReadPropertySegment()
    {
        if (this.Check(TokType.QuotedString))
            return Str(this.Advance().StringValue!);

        if (this.Check(TokType.Number))
            return JsonValue.Create(this.Advance().NumberValue);

        if (this.Check(TokType.Ident))
            return Str(this.Advance().Text);

        throw new JsonQueryParseException("Expected property name after '.'", this.Current.Position);
    }

    // name(arg1, arg2, ...)  ->  ["name", arg1, arg2, ...]
    // Includes get(...) which follows the same call syntax per the docs — no
    // special-casing needed since we never validate function names at parse
    // time (see design note on the class).
    private JsonNode ParseFunctionCall()
    {
        string name = this.Advance().Text;
        this.Expect(TokType.LParen, "'('");

        var args = new List<JsonNode?>();

        if (!this.Check(TokType.RParen))
        {
            args.Add(this.ParsePipe());
            while (this.Check(TokType.Comma))
            {
                this.Advance();
                args.Add(this.ParsePipe());
            }
        }

        this.Expect(TokType.RParen, "')'");
        return Call(name, args.ToArray());
    }

    // { prop1: query1, prop2: query2, ... }  ->  ["object", { prop1: query1, ... }]
    private JsonNode ParseObject()
    {
        this.Expect(TokType.LBrace, "'{'");
        var obj = new JsonObject();

        if (!this.Check(TokType.RBrace))
        {
            this.ParseObjectEntry(obj);
            while (this.Check(TokType.Comma))
            {
                this.Advance();
                this.ParseObjectEntry(obj);
            }
        }

        this.Expect(TokType.RBrace, "'}'");
        return Call("object", obj);
    }

    private void ParseObjectEntry(JsonObject obj)
    {
        string key = this.ReadObjectKey();
        this.Expect(TokType.Colon, "':'");
        JsonNode? value = this.ParsePipe();
        obj[key] = value;
    }

    // Object keys accept the same three source forms as a property-path
    // segment (see ReadPropertySegment): a quoted string, a bare word, or a
    // plain integer — matching the reference implementation's
    // `parseString() ?? parseUnquotedString() ?? parseInteger()`. Unlike a
    // property segment though, a key is always folded down to a JSON STRING
    // here (JsonObject, like a JS object, only has string keys) — a numeric
    // key like `{ 2: "two" }` becomes the string key "2", not a JSON number.
    //
    // True/False/Null tokens are accepted too and contribute their raw text
    // ("true"/"false"/"null") rather than their literal meaning: those three
    // words are only keywords in VALUE position. In KEY position they're
    // exactly as unremarkable as any other bareword — `{null:null}` is a
    // valid object with the string key "null" mapped to the JSON value null.
    private string ReadObjectKey()
    {
        if (this.Check(TokType.QuotedString))
            return this.Advance().StringValue!;

        if (this.Check(TokType.Number))
            return this.Advance().Text;

        if (this.Check(TokType.Ident) || this.Check(TokType.True) ||
            this.Check(TokType.False) || this.Check(TokType.Null))
            return this.Advance().Text;

        throw new JsonQueryParseException("Expected property key", this.Current.Position);
    }

    // [ item1, item2, ... ]  ->  ["array", item1, item2, ...]
    private JsonNode ParseArray()
    {
        this.Expect(TokType.LBracket, "'['");
        var items = new List<JsonNode?>();

        if (!this.Check(TokType.RBracket))
        {
            items.Add(this.ParsePipe());
            while (this.Check(TokType.Comma))
            {
                this.Advance();
                items.Add(this.ParsePipe());
            }
        }

        this.Expect(TokType.RBracket, "']'");
        return Call("array", items.ToArray());
    }
}
